//! Daily log management CLI commands.
//!
//! Provides commands for viewing, listing, promoting, and cleaning up
//! daily log files generated by the nagual hooks system. Daily logs
//! serve as a human-readable staging area before entries enter the
//! pattern store.
//!
//! # Daily Log Format
//!
//! Each daily log is a Markdown file at `memory/YYYY-MM-DD.md` with entries:
//! ```text
//! - **HH:MM:SS** [TYPE] content
//! ```
//!
//! Entry types: SESSION, EDIT, TASK, BASH, LEARNED, INSIGHT, PROMPT
//!
//! # Usage Examples
//!
//! ```bash
//! # Show today's log
//! nagual learn daily show
//!
//! # Show a specific date's log
//! nagual learn daily show --date 2026-03-07
//!
//! # List recent daily logs
//! nagual learn daily list --days 7
//!
//! # Promote LEARNED/INSIGHT entries to pattern store
//! nagual learn daily promote --date 2026-03-07
//!
//! # Clean up old daily logs (keep last 30 days)
//! nagual learn daily cleanup --keep 30
//! ```

use std::path::PathBuf;

use clap::{Args, Subcommand};

use crate::cli::common::init_storage;
use crate::error::Result;
use crate::reasoning_bank::pattern::{Pattern, PatternCategory};

/// Arguments for the daily subcommand.
#[derive(Args, Debug)]
pub struct DailyArgs {
    #[command(subcommand)]
    pub action: DailySubcommand,
}

/// Daily log management actions.
#[derive(Subcommand, Debug)]
pub enum DailySubcommand {
    /// Show a daily log file.
    Show(DailyShowArgs),
    /// List available daily log files.
    List(DailyListArgs),
    /// Promote LEARNED/INSIGHT entries to pattern store.
    Promote(DailyPromoteArgs),
    /// Clean up old daily logs.
    Cleanup(DailyCleanupArgs),
}

/// Arguments for showing a daily log.
#[derive(Args, Debug)]
pub struct DailyShowArgs {
    /// Date to show (YYYY-MM-DD). Defaults to today.
    #[arg(long)]
    pub date: Option<String>,

    /// Directory containing daily logs.
    #[arg(long, default_value = "memory")]
    pub log_dir: PathBuf,

    /// Filter by entry type (e.g., LEARNED, INSIGHT, EDIT).
    #[arg(long, short = 't')]
    pub entry_type: Option<String>,
}

/// Arguments for listing daily logs.
#[derive(Args, Debug)]
pub struct DailyListArgs {
    /// Number of recent days to list.
    #[arg(long, default_value = "7")]
    pub days: u32,

    /// Directory containing daily logs.
    #[arg(long, default_value = "memory")]
    pub log_dir: PathBuf,
}

/// Arguments for promoting daily log entries.
#[derive(Args, Debug)]
pub struct DailyPromoteArgs {
    /// Date to promote from (YYYY-MM-DD). Defaults to today.
    #[arg(long)]
    pub date: Option<String>,

    /// Directory containing daily logs.
    #[arg(long, default_value = "memory")]
    pub log_dir: PathBuf,

    /// Path to SQLite database.
    #[arg(long, default_value = "./nagual.db")]
    pub db_path: PathBuf,

    /// PostgreSQL connection URL.
    #[arg(long)]
    pub postgres_url: Option<String>,

    /// Dry run — show what would be promoted without storing.
    #[arg(long)]
    pub dry_run: bool,
}

/// Arguments for cleaning up old daily logs.
#[derive(Args, Debug)]
pub struct DailyCleanupArgs {
    /// Number of days to keep.
    #[arg(long, default_value = "30")]
    pub keep: u32,

    /// Directory containing daily logs.
    #[arg(long, default_value = "memory")]
    pub log_dir: PathBuf,

    /// Dry run — show what would be deleted without removing.
    #[arg(long)]
    pub dry_run: bool,
}

/// A parsed entry from a daily log file.
#[derive(Debug, Clone, PartialEq)]
pub struct DailyLogEntry {
    /// Timestamp in HH:MM:SS format.
    pub timestamp: String,
    /// Entry type (SESSION, EDIT, TASK, BASH, LEARNED, INSIGHT, PROMPT).
    pub entry_type: String,
    /// The content/description of the entry.
    pub content: String,
}

impl DailyLogEntry {
    /// Returns true if this entry type is promotable to the pattern store.
    pub fn is_promotable(&self) -> bool {
        matches!(
            self.entry_type.as_str(),
            "LEARNED" | "INSIGHT" | "ERROR"
        )
    }
}

/// Parse a single daily log entry line.
///
/// Expected format: `- **HH:MM:SS** [TYPE] content`
///
/// Returns `None` if the line does not match the expected format.
pub fn parse_daily_log_entry(line: &str) -> Option<DailyLogEntry> {
    let line = line.trim();

    // Must start with "- **"
    if !line.starts_with("- **") {
        return None;
    }

    // Find the closing ** for the timestamp
    let after_open = &line[4..]; // skip "- **"
    let ts_end = after_open.find("**")?;
    let timestamp = after_open[..ts_end].trim().to_string();

    // After "**" there should be " [TYPE] content"
    let rest = &after_open[ts_end + 2..]; // skip "**"
    let rest = rest.trim_start();

    // Parse [TYPE]
    if !rest.starts_with('[') {
        return None;
    }
    let bracket_end = rest.find(']')?;
    let entry_type = rest[1..bracket_end].to_string();
    let content = rest[bracket_end + 1..].trim().to_string();

    Some(DailyLogEntry {
        timestamp,
        entry_type,
        content,
    })
}

/// Parse all entries from a daily log file content.
///
/// Skips header lines, blank lines, and lines that don't match the entry format.
pub fn parse_daily_log(content: &str) -> Vec<DailyLogEntry> {
    content
        .lines()
        .filter_map(parse_daily_log_entry)
        .collect()
}

/// Get today's date in YYYY-MM-DD format (UTC).
fn today_utc() -> String {
    chrono::Utc::now().format("%Y-%m-%d").to_string()
}

/// Execute the daily command.
pub async fn run(args: &DailyArgs) -> Result<()> {
    match &args.action {
        DailySubcommand::Show(show_args) => run_show(show_args).await,
        DailySubcommand::List(list_args) => run_list(list_args).await,
        DailySubcommand::Promote(promote_args) => run_promote(promote_args).await,
        DailySubcommand::Cleanup(cleanup_args) => run_cleanup(cleanup_args).await,
    }
}

/// Show a daily log file.
async fn run_show(args: &DailyShowArgs) -> Result<()> {
    let date = args.date.clone().unwrap_or_else(today_utc);
    let log_path = args.log_dir.join(format!("{}.md", date));

    if !log_path.exists() {
        println!("No daily log found for {}", date);
        println!("  Path: {}", log_path.display());
        return Ok(());
    }

    let content = std::fs::read_to_string(&log_path)?;

    if let Some(ref filter_type) = args.entry_type {
        let filter_upper = filter_type.to_uppercase();
        let entries = parse_daily_log(&content);
        let filtered: Vec<_> = entries
            .iter()
            .filter(|e| e.entry_type == filter_upper)
            .collect();

        println!("# Daily Log: {} (filtered: {})", date, filter_upper);
        println!();
        if filtered.is_empty() {
            println!("No entries of type [{}]", filter_upper);
        } else {
            for entry in &filtered {
                println!(
                    "- **{}** [{}] {}",
                    entry.timestamp, entry.entry_type, entry.content
                );
            }
            println!();
            println!("{} entries shown", filtered.len());
        }
    } else {
        // Print the whole file
        print!("{}", content);
        let entries = parse_daily_log(&content);
        println!();
        println!("{} entries total", entries.len());
    }

    Ok(())
}

/// List available daily log files.
async fn run_list(args: &DailyListArgs) -> Result<()> {
    if !args.log_dir.exists() {
        println!("No daily logs directory found at {}", args.log_dir.display());
        return Ok(());
    }

    let mut log_files: Vec<_> = std::fs::read_dir(&args.log_dir)?
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let name = entry.file_name().to_string_lossy().to_string();
            // Match YYYY-MM-DD.md pattern
            if name.len() == 13 && name.ends_with(".md") && name.chars().nth(4) == Some('-') {
                let date = name.trim_end_matches(".md").to_string();
                // Validate it looks like a date
                if date.len() == 10
                    && date.chars().nth(7) == Some('-')
                    && date[..4].parse::<u32>().is_ok()
                {
                    let metadata = entry.metadata().ok()?;
                    let size = metadata.len();
                    Some((date, size, entry.path()))
                } else {
                    None
                }
            } else {
                None
            }
        })
        .collect();

    // Sort by date descending
    log_files.sort_by(|a, b| b.0.cmp(&a.0));

    // Limit to requested days
    log_files.truncate(args.days as usize);

    if log_files.is_empty() {
        println!("No daily logs found in {}", args.log_dir.display());
        return Ok(());
    }

    println!("Daily Logs (last {} days):", args.days);
    println!("{:<12} {:>8}  {:>6}", "Date", "Size", "Entries");
    println!("{}", "-".repeat(32));

    for (date, size, path) in &log_files {
        let entry_count = if let Ok(content) = std::fs::read_to_string(path) {
            parse_daily_log(&content).len()
        } else {
            0
        };

        let size_str = if *size > 1024 {
            format!("{:.1}KB", *size as f64 / 1024.0)
        } else {
            format!("{}B", size)
        };

        println!("{:<12} {:>8}  {:>6}", date, size_str, entry_count);
    }

    println!();
    println!("{} log files found", log_files.len());

    Ok(())
}

/// Promote LEARNED/INSIGHT entries from a daily log to the pattern store.
async fn run_promote(args: &DailyPromoteArgs) -> Result<()> {
    let date = args.date.clone().unwrap_or_else(today_utc);
    let log_path = args.log_dir.join(format!("{}.md", date));

    if !log_path.exists() {
        println!("No daily log found for {}", date);
        return Ok(());
    }

    let content = std::fs::read_to_string(&log_path)?;
    let entries = parse_daily_log(&content);
    let promotable: Vec<_> = entries.iter().filter(|e| e.is_promotable()).collect();

    if promotable.is_empty() {
        println!(
            "No promotable entries in {} ({} entries total)",
            date,
            entries.len()
        );
        println!("Promotable types: LEARNED, INSIGHT, ERROR");
        return Ok(());
    }

    println!(
        "Found {} promotable entries out of {} total in {}",
        promotable.len(),
        entries.len(),
        date
    );
    println!();

    if args.dry_run {
        println!("[DRY RUN] Would promote:");
        for entry in &promotable {
            println!(
                "  [{}] {} — {}",
                entry.entry_type, entry.timestamp, entry.content
            );
        }
        return Ok(());
    }

    let storage = init_storage(&args.db_path, args.postgres_url.as_deref()).await?;
    let mut promoted = 0;

    for entry in &promotable {
        let problem = format!(
            "[{}] {} (from daily log {})",
            entry.entry_type, entry.content, date
        );
        let solution = format!(
            "Promoted from daily log entry at {} on {}",
            entry.timestamp, date
        );

        let pattern = Pattern::builder()
            .problem(&problem)
            .solution(&solution)
            .category(PatternCategory::Custom("daily-promoted".to_string()))
            .tag("daily-promoted")
            .tag(&entry.entry_type.to_lowercase())
            .tag(&date)
            .build();

        match storage.store_pattern(&pattern).await {
            Ok(_) => {
                promoted += 1;
                println!("  Promoted: [{}] {}", entry.entry_type, entry.content);
            }
            Err(e) => {
                eprintln!(
                    "  Failed to promote [{}] {}: {}",
                    entry.entry_type, entry.content, e
                );
            }
        }
    }

    println!();
    println!("{} / {} entries promoted to pattern store", promoted, promotable.len());

    Ok(())
}

/// Clean up old daily logs.
async fn run_cleanup(args: &DailyCleanupArgs) -> Result<()> {
    if !args.log_dir.exists() {
        println!("No daily logs directory found at {}", args.log_dir.display());
        return Ok(());
    }

    let today = chrono::Utc::now().date_naive();
    let keep_days = chrono::Duration::days(args.keep as i64);
    let cutoff = today - keep_days;

    let mut removed = 0;
    let mut kept = 0;

    let mut entries: Vec<_> = std::fs::read_dir(&args.log_dir)?
        .filter_map(|e| e.ok())
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let name = entry.file_name().to_string_lossy().to_string();

        // Only process YYYY-MM-DD.md files
        if !name.ends_with(".md") || name.len() != 13 {
            continue;
        }
        // Skip README.md or other non-date files
        let date_str = name.trim_end_matches(".md");
        let file_date = match chrono::NaiveDate::parse_from_str(date_str, "%Y-%m-%d") {
            Ok(d) => d,
            Err(_) => continue,
        };

        if file_date < cutoff {
            if args.dry_run {
                println!("[DRY RUN] Would remove: {}", name);
            } else {
                match std::fs::remove_file(entry.path()) {
                    Ok(_) => println!("Removed: {}", name),
                    Err(e) => eprintln!("Failed to remove {}: {}", name, e),
                }
            }
            removed += 1;
        } else {
            kept += 1;
        }
    }

    if args.dry_run {
        println!();
        println!(
            "[DRY RUN] Would remove {} logs, keep {} (cutoff: {})",
            removed, kept, cutoff
        );
    } else {
        println!();
        println!(
            "Removed {} old logs, kept {} (cutoff: {})",
            removed, kept, cutoff
        );
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_daily_log_entry() {
        let line = "- **14:30:22** [LEARNED] Fixed async timeout by adding tokio::time::timeout";
        let entry = parse_daily_log_entry(line).unwrap();
        assert_eq!(entry.timestamp, "14:30:22");
        assert_eq!(entry.entry_type, "LEARNED");
        assert!(entry.content.contains("async timeout"));
        assert_eq!(
            entry.content,
            "Fixed async timeout by adding tokio::time::timeout"
        );
    }

    #[test]
    fn test_parse_daily_log_entry_various_types() {
        let cases = vec![
            (
                "- **10:00:00** [SESSION] Session started (domain: general)",
                "SESSION",
                "Session started (domain: general)",
            ),
            (
                "- **10:05:12** [EDIT] src/main.rs (true)",
                "EDIT",
                "src/main.rs (true)",
            ),
            (
                "- **11:30:45** [TASK] Implement feature X (true)",
                "TASK",
                "Implement feature X (true)",
            ),
            (
                "- **12:00:00** [BASH] cargo build --release (true)",
                "BASH",
                "cargo build --release (true)",
            ),
            (
                "- **13:15:00** [INSIGHT] rust: Lifetimes can be elided in most cases",
                "INSIGHT",
                "rust: Lifetimes can be elided in most cases",
            ),
        ];

        for (line, expected_type, expected_content) in cases {
            let entry = parse_daily_log_entry(line).unwrap();
            assert_eq!(entry.entry_type, expected_type, "Failed for line: {}", line);
            assert_eq!(
                entry.content, expected_content,
                "Failed for line: {}",
                line
            );
        }
    }

    #[test]
    fn test_parse_daily_log_entry_invalid_lines() {
        // Header lines and non-entry lines should return None
        assert!(parse_daily_log_entry("# Daily Log: 2026-03-08").is_none());
        assert!(parse_daily_log_entry("").is_none());
        assert!(parse_daily_log_entry("---").is_none());
        assert!(parse_daily_log_entry("> Auto-generated by nagual hooks.").is_none());
        assert!(parse_daily_log_entry("Some random text").is_none());
        // Missing bracket
        assert!(parse_daily_log_entry("- **10:00:00** SESSION started").is_none());
    }

    #[test]
    fn test_parse_daily_log_full() {
        let content = r#"# Daily Log: 2026-03-08

> Auto-generated by nagual hooks. Review at session end for pattern promotion.

---

- **10:00:00** [SESSION] Started
- **10:05:00** [EDIT] src/main.rs (true)
- **10:10:00** [LEARNED] Fixed borrow checker issue with Arc<Mutex>
- **10:15:00** [INSIGHT] rust: Use Arc::clone for clarity
- **10:20:00** [BASH] cargo test --lib (true)
"#;
        let entries = parse_daily_log(content);
        assert_eq!(entries.len(), 5);
        assert_eq!(entries[0].entry_type, "SESSION");
        assert_eq!(entries[1].entry_type, "EDIT");
        assert_eq!(entries[2].entry_type, "LEARNED");
        assert_eq!(entries[3].entry_type, "INSIGHT");
        assert_eq!(entries[4].entry_type, "BASH");
    }

    #[test]
    fn test_daily_log_promotable_filter() {
        let content = r#"# Daily Log: 2026-03-08

---

- **10:00:00** [SESSION] Started
- **10:05:00** [EDIT] src/main.rs (true)
- **10:10:00** [LEARNED] Fixed borrow checker issue
- **10:15:00** [INSIGHT] Use Arc::clone for clarity
- **10:20:00** [BASH] cargo test --lib (true)
- **10:25:00** [TASK] Implement feature X (true)
- **10:30:00** [ERROR] Missing semicolon in parser
"#;
        let entries = parse_daily_log(content);
        assert_eq!(entries.len(), 7);

        let promotable: Vec<_> = entries.iter().filter(|e| e.is_promotable()).collect();
        assert_eq!(promotable.len(), 3);
        assert_eq!(promotable[0].entry_type, "LEARNED");
        assert_eq!(promotable[1].entry_type, "INSIGHT");
        assert_eq!(promotable[2].entry_type, "ERROR");
    }

    #[test]
    fn test_daily_subcommand_parsing() {
        // Verify the enum variants exist and DailyLogEntry fields are accessible
        let entry = DailyLogEntry {
            timestamp: "14:30:00".to_string(),
            entry_type: "LEARNED".to_string(),
            content: "Test content".to_string(),
        };
        assert!(entry.is_promotable());

        let edit_entry = DailyLogEntry {
            timestamp: "14:30:00".to_string(),
            entry_type: "EDIT".to_string(),
            content: "src/main.rs".to_string(),
        };
        assert!(!edit_entry.is_promotable());

        let session_entry = DailyLogEntry {
            timestamp: "14:30:00".to_string(),
            entry_type: "SESSION".to_string(),
            content: "Started".to_string(),
        };
        assert!(!session_entry.is_promotable());
    }

    #[test]
    fn test_parse_daily_log_empty() {
        let content = "";
        let entries = parse_daily_log(content);
        assert!(entries.is_empty());
    }

    #[test]
    fn test_parse_daily_log_header_only() {
        let content = "# Daily Log: 2026-03-08\n\n> Auto-generated.\n\n---\n\n";
        let entries = parse_daily_log(content);
        assert!(entries.is_empty());
    }
}
